backend:
  name: git-gateway
  branch: netlifycms
media_folder: public/img
public_folder: img
collections:
  - name: "team"
    label: "Team"
    files:
    - name: "team"
      label: "Team"
      file: "content/team.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - label: 'Persons'
          name: "persons"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Avatar", name: "avatar", widget: "string"}
            - { label: "Facebook", name: "fb", widget: "string"}
            - { label: "Github", name: "github", widget: "string"}
            - { label: "Email", name: "email", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}